name: DAO of the Ring WEBAPP - PROD - CI/CD Docker & AWS

on:
  push:
    branches:
      - main
    paths:
      - ""

env:
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
  SSH_USER: ${{ secrets.EC2_USERNAME }}
  SSH_HOST: ${{ secrets.EC2_URL }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: daoofthering-webapp
  APP_NAME: dao-ring-webapp

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
          build-args: |

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_URL }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop nginx
            sudo docker stop ${{ env.APP_NAME }} || true
            docker rm ${{ env.APP_NAME }} || true
            sudo docker images ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }} -q | xargs -r sudo docker rmi || true
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
            sudo docker run --name ${{ env.APP_NAME }} -p 8080:8080 --restart=always -d ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
            sudo systemctl start nginx
